services:
  api: &api
    build:
      context: ./api
      dockerfile: docker/local/django/Dockerfile
    image: department_prod_api
    container_name: department_prod_api
    volumes:
      - ./api:/app:z
      - ./api/staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./api/.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
    command: /start
    networks:
      - department_prod_nw

  postgres:
    build:
      context: ./api
      dockerfile: docker/local/postgres/Dockerfile
    image: department_prod_postgres
    container_name: department_prod_postgres
    ports:
      - "5432:5432"
    volumes:
      - department_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./api/.envs/.env.local
    networks:
      - department_prod_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: department_prod_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - department_prod_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - department_prod_nw

  client:
    build:
      context: ./client
      dockerfile: docker/local/Dockerfile
    container_name: department_client
    image: department_client
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - department_prod_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: department_redis
    volumes:
      - department_redis_prod_data:/data
    networks:
      - department_prod_nw

  celeryworker:
    <<: *api
    image: department_prod_celeryworker
    container_name: department_prod_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *api
    image: department_prod_celerybeat
    container_name: department_prod_celerybeat
    command: /start-celerybeat

  flower:
    <<: *api
    image: department_prod_flower
    container_name: department_prod_flower
    ports:
      - "5555:5555"
    command: /start-flower

  nginx:
    build:
      context: ./api/docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: department_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api/staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - department_prod_nw
networks:
  department_prod_nw:

volumes:
  department_prod_postgres_data: {}
  department_prod_mailpit_data: {}
  logs_store: {}
  department_redis_prod_data: {}
